filebeat.inputs:

- input_type: log

  paths:
    - /usr/local/logs/app-elk.log
  #定义写入ES时的 _type 值
  document_type: "app-log"
  multiline:
    pattern: '^\['						# 指定匹配的表达式（匹配以‘[’开头的字符串）
    negate: true							# 是否匹配到
    match: after							# 合并到上一行的末尾
    max_lines: 2000						# 最大的行数
    timeout: 2s								# 如果在规定时间没有新的日志事件就不等待后面的日志
  fields:
    logbiz: elk
    logtopic: app-log-elk			# 按服务划分用作kafka topic
    env: dev

- input_type: log

  paths:
    - /usr/local/logs/error-elk.log
  #定义写入ES时的 _type 值
  document_type: "error-log"
  multiline:
    pattern: '^\['						# 指定匹配的表达式（匹配以‘[’开头的字符串）
    negate: true							# 是否匹配到
    match: after							# 合并到上一行的末尾
    max_lines: 2000						# 最大的行数
    timeout: 2s								# 如果在规定时间没有新的日志事件就不等待后面的日志
  fields:
    logbiz: elk
    logtopic: error-log-elk			# 按服务划分用作kafka topic
    env: dev

output.kafka:
  enabled: true
  hosts: ["localhost:9092"]
  topic: '%{[fields.logtopic]}'
  partition.hash:
    reachable_only: true
  compression: gzip
  max_message_bytes: 1000000
  required_acks: 1
logging.to_files: true